### ISSUE TITLE
deps.txt

### ISSUE THREAD

**Issue by sylarKYG** [lkalmar/HAM-ART#1]
I created the conda env hamart, and installed bowtie2, spades, abricate, samtools.pl, blast+, and mash using conda. I downloaded the clumpify.sh, and flash into my own folder, and add the path in the deps.txt. how to install louvain software and gtdbtk? and I add the julia into $PATH.

**Comment by lkalmar** [comment]
Hi, The HAM-ART is using the Louvain implementation from here: [SourceForge link](https://sourceforge.net/projects/louvain/files/), using the generic linux one. GTDB-tk is a bit trickier to install and I recommend to create a separate conda env for it, just follow their [installation instructions](https://ecogenomics.github.io/GTDBTk/installing/index.html).

**Comment by sylarKYG** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you for the reply.
    
        
            
        
    
    
        
        

        
    

    On 4/4/2022 ***@***.***> wrote： 



Hi, The HAM-ART is using the Louvain implementation from here: SourceForge link, using the generic linux one. GTDB-tk is a bit trickier to install and I recommend to create a separate conda env for it, just follow their installation instructions.
