### ISSUE TITLE
Initialise step not working.

### ISSUE THREAD

**Issue by ABignaud** [lkalmar/HAM-ART#2]
Hi,

I have installed and followed all your setup steps and install all the dependencies. Once, I launch the `initialise` step, nothing happens. It just lasts one second and I don't get any error/output message:

Here is my command line:
```bash
cd project_defs/
../ham_art.pl initialise sample_001.txt
```

The only error message, I manage to get is the one deliver if you run second command outside a project_defs repository. 
Thanks for your help,

**Comment by lkalmar** [comment]
> 

Can you please copy the content of your sample_001.txt file here?

**Comment by ABignaud** [comment]
Here is my file:

```
#Please define the basic parameters for you project on the Metagenomics and Hi-C pipeline
#Please do not edit this file, but copy first to the "project_defs/" folder and edit your working copy
#For copying, use: "cp -i ham_art_prj_template.txt project_defs/<your_project_filename>.txt"
#Edit only lines not starting with #
#All parameters are defined by a pair of strigs, the name of the parameter and its value separated by a whitespace (tabulator or space)
#Please do not use whitespace in filename (using underline "_" is allowed)
#
#Project identifier (has to be unique, e.g. p01001)
PRJID sample_001
#
#Metagenomics reads full file names (for mate 1 and 2). Only the filename without the path.
METF1 SH11_R1.fq.gz
METF1 SH11_R2.fq.gz
#
#Hi-C reads full file names (for mate 1 and 2). Only the filename without the path.
METF1 SH4_R1.fq.gz
METF1 SH4_R2.fq.gz
#
#Project category (the folder name in "raw_seq_data" folder where the reads can be found, like "conv_and_org_farm")
PRJF sample
#
#Project host species: pig, human, chicken, cow  (if prjid = p01001, then the host is  "pig")
#If your sample has no defined host organism (e.g. soil sample, waste-water treatment sediment sample) please use "NOHOST" in the second field
PRJH NOHOST
```

**Comment by lkalmar** [comment]
I guess you have the "raw_seq_data" folder in your ham-art root, and you have a "sample" subfolder in it with these file names. 

I checked the script file and found a few bugs in it that is now repaired, so please download / comit the new version (only the ham_art.pl has changed).

Also please be aware that in your sample_001.txt file you use the same prefix for all your filenames, it should be METF1 and METF2 for the metagenomics and HICF1 and HICF2 for the Hi-C library files (as it is in the ham_art_prj_template.txt file).

**Comment by ABignaud** [comment]
Yes the SH4 is a metaHiC sample and the SH11 is the genomic libraries made on the same sample.

**Comment by ABignaud** [comment]
I tried with the new file I don't have any differences.

**Comment by ABignaud** [comment]
Here is the tree of the HAM-ART repository:

```
.
├── assembly
├── deps.txt
├── ham_art.pl
├── host_ref_seqs
├── post_assembly
├── pre_assembly
├── project_defs
│   ├── sample_001.txt
│   ├── sample_002.txt
│   ├── sample_003.txt
│   ├── sample_004.txt
│   ├── sample_005.txt
│   ├── sample_006.txt
│   └── sample_007.txt
├── raw_seq_data
│   └── sample
│       ├── SH10_R1.fq.gz
│       ├── SH10_R2.fq.gz
│       ├── SH11_R1.fq.gz
│       ├── SH11_R2.fq.gz
│       ├── SH12_R1.fq.gz
│       ├── SH12_R2.fq.gz
│       ├── SH13_R1.fq.gz
│       ├── SH13_R2.fq.gz
│       ├── SH14_R1.fq.gz
│       ├── SH14_R2.fq.gz
│       ├── SH15_R1.fq.gz
│       ├── SH15_R2.fq.gz
│       ├── SH2_R1.fq.gz
│       ├── SH2_R2.fq.gz
│       ├── SH3_R1.fq.gz
│       ├── SH3_R2.fq.gz
│       ├── SH4_R1.fq.gz
│       ├── SH4_R2.fq.gz
│       ├── SH5_R1.fq.gz
│       ├── SH5_R2.fq.gz
│       ├── SH6_R1.fq.gz
│       ├── SH6_R2.fq.gz
│       ├── SH7_R1.fq.gz 
│       ├── SH7_R2.fq.gz
│       ├── SH8_R1.fq.gz
│       ├── SH8_R2.fq.gz
│       ├── SH9_R1.fq.gz
│       └── SH9_R2.fq.gz
└── results
```

**Comment by lkalmar** [comment]
Have you also updated your local copy of the ham_art.pl script? I did some bug fixes in it, so you have to download it from here.

**Comment by ABignaud** [comment]
Yes I have cloned the repo and updated the  `ham_art.pl` script inside the repository. I didn't change any other files.

**Comment by lkalmar** [comment]
Found the bug, please update your local copy of `ham_art.pl` and try to initialise again. I tried, it worked for me.

**Comment by ABignaud** [comment]
Thank you, it works.
