### ISSUE TITLE
Path not found in the pre assembly step

### ISSUE THREAD

**Issue by ABignaud** [lkalmar/HAM-ART#3]
Hi, 
I try to launch the pre-assembly step after the initialise step. However I get this error message. 

```
./ham_art.pl pre_assembly sample_001
Running de-duplication on the metagenomics dataset
Raw data fastq files cannot be found!
```
I launch it from the 'HAM-ART root folder' and here are the project files.

My project_defs/projects_db.txt file:

```
sample_001                      project_defs//home/login/projets/HAM_ART/project_defs/sample_001.txt          init;
```

My project_defs/sample_001.txt file:

```
#Please define the basic parameters for you project on the Metagenomics and Hi-C pipeline
#Please do not edit this file, but copy first to the "project_defs/" folder and edit your working copy
#For copying, use: "cp -i ham_art_prj_template.txt project_defs/<your_project_filename>.txt"
#Edit only lines not starting with #
#All parameters are defined by a pair of strigs, the name of the parameter and its value separated by a whitespace (tabulator or space)
#Please do not use whitespace in filename (using underline "_" is allowed)
#
#Project identifier (has to be unique, e.g. p01001)
PRJID sample_001
#
#Metagenomics reads full file names (for mate 1 and 2). Only the filename without the path.
METF1 SH9_R1.fq.gz
METF2 SH9_R2.fq.gz
#
#Hi-C reads full file names (for mate 1 and 2). Only the filename without the path.
HICF1 SH2_R1.fq.gz
HICF2 SH2_R2.fq.gz
#
#Project category (the folder name in "raw_seq_data" folder where the reads can be found, like "conv_and_org_farm")
PRJF sample
#
#Project host species: pig, human, chicken, cow  (if prjid = p01001, then the host is  "pig")
#If your sample has no defined host organism (e.g. soil sample, waste-water treatment sediment sample) please use "NOHOST" in the second field
PRJH NOHOST
```

I look in the code and it seems that the `$prj{'METF1'}` is empty as all the others variables contained in `$prj`, like the variables are not set.

Thanks for your help.

**Comment by lkalmar** [comment]
Hi, it seems to me that you ran the initialisation step with the full path to the filename. That part is written in a way that you should only give the file name (without path), because you are in the `project_defs` folder. Your projects_db.txt file should contain the project ID, a date string (I don't know why it is not there) the relative path to the file (relative from the HAM-ART root, so `project_defs/filename`, followed by the md5 hash string of the config file (just to check later that it wasn't modified) and in the last column the last step that was taken. I did a small modification in the `ham_art.pl` as I found an unnecessary extra column (that we used on our HPC, but should be blank for you), but this wasn't the problem in your case. If you want, you can update the script, just to have the latest one. So please remove the projects_db.txt file (or just this line from it if you have more) and re-run the initialisation step by being in the `project_defs` folder and using the `../ham_art.pl initialise sample_001.txt` command (again, just the filename without the path).

**Comment by lkalmar** [comment]
I tried yesterday with the same project config file, and it worked me well, the line for me looks like:
`sample_001              18_10_2022      project_defs/sample_001.txt     ed883cd00532393988c038a201389992        init;`

**Comment by ABignaud** [comment]
Hi, 
I am also working on a HPC, launching the scripts with the local path makes it works. Bu I had to update with your new version to have the date, and the md5sum. 
However, it seems that it's still not able to find/read the deps.txt file which is in the same directory. I checked, I have the clumpify.sh in my path and the command works (at least with the metagenomic samples).

Here is the output I have, nothing happens and no output are written:
```
Running de-duplication on the metagenomics dataset
Running de-duplication on the Hi-C dataset
Skipping de-hosting step.
mv: cannot stat 'pre_assembly/sample/sample_001_meta_dedup.r_1.fq': No such file or directory
mv: cannot stat 'pre_assembly/sample/sample_001_meta_dedup.r_2.fq': No such file or directory
Megring overlapping reads in the metagenomics dataset
Megring overlapping reads in the Hi-C dataset
```

Here is my deps.txt file:

```
# This file contains the paths to programs used by the HAM-ART pipeline
# The pipeline only reads in lines without starting #
#
# Each software  has an internal identifier (first column)
# a recommended number of CPUs / threads and/or memory to use (second column)
# and a path to the executable (third colum)
#
# Please don't change the internal identifier!
# If you have the software in your path, leave the executable name in the third column
# If the software is not in your path, please provide the full path to the executable
# Please change the number of CPUs / threads / memory if you don't have the required amount available
#
# The pipeline was optimised on a system with maximum of 32 CPU cores.
# If you have more CPU cores / threads available, you may increase the performance of those
# applications that have a reccomended CPU cores set to 32
#
#
# path to clupify.sh in bbmap package (second column sets the memory to be used in gigabytes)
CLUMPIFY 96 clumpify.sh
# path to the bowtie2 executable (second column sets the number of threads to be used)
BOWTIE2 32 bowtie2
# path to the flash (Fast Length Adjustment of SHort reads) executable, second column sets the number of threads to be used
FLASH 12 flash
# path to metaspades.py script (Spades software package),
# second column sets the number of CPUs and the amount of memory (in GB) to be used (separated by comma)
METASPADES 64,384 metaspades.py
# path to bowtie2-build for building database (running on default settings)
BOWTIE2-B default bowtie2-build
# path to the abricate executable (second column sets the number of threads to use in BLAST)
ABRICATE 32 abricate
# path to samtools software (second collumn sets the number of threads to be used)
SAMTOOLS 32 samtools
# path to louvain software folder (please provide the full path to the folder with executables convert, hierarchy, louvain, etc. here)
LOUVAIN default /home/projets/external/gen-louvain
# path to makeblastdb executable
MAKEBLDB default makeblastdb
# path to blastn executable
BLASTN 4 blastn
# path to mash (Fast genome and metagenome distance estimation using MinHash) software, second column sets the number of threads to be used
MASH default mash
#path to GTDBTK software executable (second column sets the CPU threads to be used)
GTDBTK 4 gtdbtk
#path to GTDBTK database folder (with the genome fasta files in it)
GTDBF default /opt/gensoft/data/GTDBTk/2.1.1
```

**Comment by lkalmar** [comment]
I have a feeling that during the deposition in github the deps.txt file field separators were changed. Originally the script expects tabulators between the fileds (like `CLUMPIFY<tab>96<tab>clumpify.sh`) but it is clearly a single space now. I re-wrote the ham_art.pl script, now it works with any whitespace. Please update it and try again.

**Comment by ABignaud** [comment]
Thanks, it works now.
